---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zkq.
--- DateTime: 2019/12/31 4:22 PM
---

functions = require "skywalking5.base.functions"
cjson = require "cjson"
http  = require "resty.http"

uuid = require 'skywalking5.resty.jit-uuid'
uuid.seed()

-- 在uuid之后
skywalking_dict = ngx.shared.skywalking_dict
skywalking_config = require("skywalking5.config")

-- 设置随机种子
math.randomseed(tostring(os.time()):reverse():sub(1, 7))

-- 注册application id和instance id
if 0 == ngx.worker.id() then
    local skywalking_register = require "skywalking5.phase.init_worker.app_and_service_register_client"
    local ok,err = pcall(skywalking_register.skywalking_timer)
    if not ok then
        ngx.log(ngx.ERR, "failed to create skywalking_timer: ", err)
        return
    end
end
